# Generated by Django 3.2.6 on 2022-01-07 09:55

from django.db import migrations, models
import user.services


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=user.services.upload_profile_image),
        ),
    ]
