# Generated by Django 3.2.6 on 2022-01-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temparature',
            field=models.FloatField(default=36.5),
        ),
    ]
