# Generated by Django 3.2.6 on 2022-01-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='valid_user',
            field=models.CharField(default='sb', max_length=2, null=True),
        ),
    ]
