# Generated by Django 3.2.6 on 2022-01-07 09:55

from django.db import migrations, models
import user.services


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='product_image',
            field=models.ImageField(blank=True, upload_to=user.services.upload_product_image),
        ),
    ]
