# Generated by Django 3.2.6 on 2022-01-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
