# Generated by Django 3.2.6 on 2022-01-07 17:58

from django.db import migrations, models
import django.db.models.deletion
import user.services


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to=user.services.upload_product_image)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='article.article')),
            ],
        ),
    ]
