# Generated by Django 3.2.6 on 2022-01-14 13:53

from django.conf import settings
from django.db import migrations, models
import imagekit.models.fields
import user.services


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_auto_20220108_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='product_image',
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=user.services.upload_product_image),
        ),
    ]
