# Generated by Django 3.2.6 on 2022-01-27 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0007_article_hit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temparature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temparature', models.FloatField(default=36.5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tempfield', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('buyer', 'buyer'), ('seller', 'seller'), ('user', 'user')], max_length=20)),
                ('review', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manner_type', models.CharField(choices=[('good', 'good'), ('bad', 'bad')], max_length=20)),
                ('manner', models.CharField(max_length=100)),
                ('article', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('review_location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_by', to=settings.AUTH_USER_MODEL)),
                ('reviewyee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_about', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
