# Generated by Django 3.2.6 on 2022-01-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_hit'),
        ('review', '0002_delete_temparature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='article',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.article'),
        ),
    ]
