name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.ROOT_PSWORD }}
          MYSQL_DATABASE: wafflemarket_backend
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python $
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd wafflemarket
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Creating Mysql User
      run: |
        mysql.server start
        mysql -uroot -p${{ secrets.ROOT_PSWORD }} -e "create user 'wafflemarket-backend'@'localhost' identified by 'password';grant all privileges on wafflemarket_backend.* to 'wafflemarket-backend'@'localhost';"
    - name: Run Migrations
      run: |
        python manage.py migrate
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: wafflemarket_backend
        DBUSER: wafflemarket-backend
        DBPASSWORD: password
        DBHOST: 127.0.0.1
        DBPORT: 3306
    - name: Run Tests
      run: |
        python manage.py test
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: wafflemarket_backend
        DBUSER: wafflemarket-backend
        DBPASSWORD: password
        DBHOST: 127.0.0.1
        DBPORT: 3306